# Change these first
owner: xjoylu # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
- name: 卢东东
  url: https://ldd.cc
- name: 三义栈
  url: https://3ez.cn
- name: 序章官网
  url: https://xuzh.com
- name: 无所事事
  url: https://wusuoshishi.com
- name: LCC
  url: https://lcc.cc
- name: PJ
  url: https://peijin.cn
  port: 80
  check: "tcp-ping"
  ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ldd.cc
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 云服务健康看板
  introTitle: "**云服务健康看板** by [Ldd](https://ldd.cc)"
  introMessage: 这是一个实时、纯前端的云服务状态监控面板，用于展示多个自有域名或服务的在线状态与响应速度。无需登录、无需后端部署，一键查看所有服务的健康状况，帮助开发者与运营者第一时间掌握网站可用性。技术支持：[卢东东](https://ldd.cc)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
